'use strict';
const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');const {randomUUID}=require('node:crypto');
const {LeadStore}=require('./store.cjs');const {createReceiver}=require('./server.cjs');const {runJob}=require('./delivery.cjs');const {_internals:h}=require('../yandex-lead-receiver/index.js');
const payload={parentName:'Test Parent',contact:'9990000000',childName:'Test Child',childAge:'9',questSlug:'test',questTitle:'Test',offerId:'test-offer',venueSlug:'test-venue',venueName:'Test Venue',leadType:'waitlist',registrationChannel:'brainmaster',consent:true};
const lead=()=>h.normalizeLead(payload,'');
test('durable atomic receipt survives restart, deduplicates changed timestamps and rejects ID conflicts',async()=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'bm-lead-'));const file=path.join(dir,'leads.sqlite');let store=new LeadStore(file);try{
 const id=randomUUID(),one=store.accept(lead(),id);assert.equal(store.summary().reduce((n,r)=>n+r.count,0),3);await store.backup();assert.equal(fs.statSync(file).mode&0o777,0o600);store.close();store=new LeadStore(file);
 assert.deepEqual(store.accept({...lead(),consentAt:'later',submittedAt:'later'},id),{receiptId:one.receiptId,duplicate:true});assert.throws(()=>store.accept({...lead(),childName:'Different'},id),{status:409});assert.equal(store.db.prepare('select count(*) n from receipts').get().n,1);
 const before=store.summary();store.db.exec("CREATE TRIGGER reject_job BEFORE INSERT ON jobs BEGIN SELECT RAISE(ABORT,'disk simulation'); END;");assert.throws(()=>store.accept({...lead(),offerId:'different'},randomUUID()));assert.equal(store.db.prepare('select count(*) n from receipts').get().n,1);assert.deepEqual(store.summary(),before);
 }finally{store.close();fs.rmSync(dir,{recursive:true,force:true});}
});
test('restart retains ambiguous sending without another POST',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'bm-lead-'));const file=path.join(dir,'q.sqlite');let store=new LeadStore(file);try{store.accept(lead(),randomUUID());assert.ok(store.claim('telegram'));store.close();store=new LeadStore(file);assert.equal(store.claim('telegram'),null);assert.equal(store.summary().find(r=>r.channel==='telegram').state,'uncertain');assert.ok(store.claim('sheets'));}finally{store.close();fs.rmSync(dir,{recursive:true,force:true});}});
test('independent channels: Telegram uncertainty cannot block Sheets; MAX can safely retry before send',async()=>{
 const previous={...process.env};Object.assign(process.env,{TELEGRAM_BOT_TOKEN:'test',TELEGRAM_CHAT_ID:'1',GOOGLE_SERVICE_ACCOUNT_JSON_BASE64:'test',GOOGLE_SHEETS_SPREADSHEET_ID:'test',GOOGLE_LEADS_SHEET_RANGE:'Leads!A:U',MAX_BOT_TOKEN:'test',MAX_ADMIN_USER_ID:'1'});const store=new LeadStore(':memory:');try{store.accept(lead(),randomUUID());let calls=[];const adapter=async c=>{calls.push(c);if(c==='telegram')throw Object.assign(Error(),{safeRetry:false});if(c==='max')throw Object.assign(Error(),{safeRetry:true});};await Promise.all(['telegram','sheets','max'].map(c=>runJob(store,c,adapter)));const states=Object.fromEntries(store.summary().map(r=>[r.channel,r.state]));assert.deepEqual(states,{max:'retry',sheets:'confirmed',telegram:'uncertain'});await runJob(store,'telegram',adapter);assert.equal(calls.filter(c=>c==='telegram').length,1);}finally{store.close();for(const k of Object.keys(process.env))if(!(k in previous))delete process.env[k];Object.assign(process.env,previous);}
});
test('missing MAX configuration is explicit and can be enabled without losing jobs',()=>{const store=new LeadStore(':memory:');try{store.accept(lead(),randomUUID());store.configured('max',false);assert.equal(store.claim('max'),null);assert.equal(store.summary().find(r=>r.channel==='max').state,'not_configured');store.configured('max',true);assert.ok(store.claim('max'));}finally{store.close();}});
test('HTTP acknowledges durable save only, enforces origin/body and separates anonymous events',async()=>{
 const store=new LeadStore(':memory:');let events=0;const server=createReceiver({store,handler:async()=>{events++;return {statusCode:202,body:JSON.stringify({ok:true,notified:false})};},validate:h.validateLeadPayload,normalize:h.normalizeLead,origins:['https://b-master.pro']});await new Promise(r=>server.listen(0,'127.0.0.1',r));const url=`http://127.0.0.1:${server.address().port}/`;const send=(data,origin='https://b-master.pro')=>fetch(url,{method:'POST',headers:{Origin:origin,'Content-Type':'application/json'},body:typeof data==='string'?data:JSON.stringify(data)});
 try{assert.equal((await send(payload,'https://evil.test')).status,403);assert.equal((await send('{')).status,400);assert.equal((await send(' '.repeat(65537))).status,413);
 const id=randomUUID(),r=await send({...payload,submissionId:id});assert.equal(r.status,202);const saved=await r.json();assert.equal(saved.status,'saved');assert.equal(store.db.prepare('select count(*) n from receipts').get().n,1);assert.equal((await (await send({...payload,submissionId:id})).json()).receiptId,saved.receiptId);assert.equal((await send({...payload,childName:'Other',submissionId:id})).status,409);
 assert.equal((await send({event:'booking.mos_click'})).status,202);assert.equal(events,1);assert.equal(store.db.prepare('select count(*) n from receipts').get().n,1);assert.equal((await fetch(url+'status')).status,404);
 store.close();const failure=await send({...payload,submissionId:randomUUID()});assert.equal(failure.status,503);assert.equal((await failure.json()).ok,false);
 }finally{await new Promise(r=>server.close(r));}
});
